# User login.
login: javaeeeee
# User  password.
password: crimson

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: pikachu@123
  url: jdbc:mysql://localhost:3306/DWGettingStarted
